version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: develop
    ports:
      - 9080:9080
    volumes:
      - .:/want-this-backend
      - cargo-target:/tmp/cargo/target
    environment:
      - CARGO_BUILD_TARGET_DIR=/tmp/cargo/target
      - DATABASE_URL=mysql://${MARIADB_USER}:${MARIADB_PASSWORD}@db:3306/${MARIADB_DATABASE}
    command: /bin/bash -c "cargo watch -w backend -x 'run -p want-this-backend'"
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - want_this_network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: develop
    ports:
      - 8080:8080
    volumes:
      - .:/want-this-frontend
      - cargo-target:/tmp/cargo/target
    environment:
      - CARGO_BUILD_TARGET_DIR=/tmp/cargo/target
    command: /bin/bash -c "trunk serve"
    networks:
      - want_this_network

  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - 3306:3306
    networks:
      want_this_network:
        ipv4_address: 172.18.0.2

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis/conf:/usr/local/etc/redis
    networks:
      - want_this_network

volumes:
  cargo-target:


networks:
  want_this_network:
    driver: bridge
    driver_opts:
      com.docker.networks.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/20
          gateway: 172.18.0.1
