[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-files = "0.6"
actix-session = "0.5"

async-stream = "0.3"
env_logger = "0.9"
log = "0.4"
serde = "*"